using Maui.AutoSuggestBox.Handlers;

namespace Maui.AutoSuggestBox;

/// <summary>
/// This class contains AutoSuggestBox <see cref="MauiAppBuilder"/> extensions.
/// </summary>
public static class AppBuilderExtensions
{
    /// <summary>
    /// Initializes the AutoSuggestBox control
    /// </summary>
    /// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/>.</param>
    /// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="AutoSuggestBox"/>.</returns>
    public static MauiAppBuilder UseAutoSuggestBox(this MauiAppBuilder builder)
    {
        builder.ConfigureMauiHandlers(h => h.AddHandler<IAutoSuggestBox, AutoSuggestBoxHandler>());

        return builder;
    }
}